# Site settings
title: Ashraf Wani
description: "Microsoft Certified Professional Developer"
baseurl: ""
url: "http://ashrafwani.com"
author: "Ashraf Wani"
name: Ashraf Wani
email: im@ashrafwani.com
uri: http://ashrafwani.com/about

# Build settings
markdown: kramdown
permalink: pretty

# Gems
gems:
   - jekyll-sitemap
gems:
  - jekyll-feed
